/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BrokerProfile = IDL.Record({
  'bio' : IDL.Text,
  'title' : IDL.Text,
  'name' : IDL.Text,
  'photoUrl' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Time = IDL.Int;
export const PropertyListing = IDL.Record({
  'zip' : IDL.Text,
  'status' : IDL.Variant({ 'sold' : IDL.Null, 'available' : IDL.Null }),
  'title' : IDL.Text,
  'created' : Time,
  'acreage' : IDL.Float64,
  'description' : IDL.Text,
  'propertyId' : IDL.Nat,
  'state' : IDL.Text,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'landType' : IDL.Variant({
    'timber' : IDL.Null,
    'commercial' : IDL.Null,
    'agricultural' : IDL.Null,
    'residential' : IDL.Null,
    'recreational' : IDL.Null,
  }),
  'price' : IDL.Nat,
  'county' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ContactInquiry = IDL.Record({
  'name' : IDL.Text,
  'propertyId' : IDL.Opt(IDL.Nat),
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBrokerProfile' : IDL.Func([BrokerProfile], [IDL.Nat], []),
  'addListing' : IDL.Func([PropertyListing], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllBrokerProfiles' : IDL.Func([], [IDL.Vec(BrokerProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeaturedListings' : IDL.Func([], [IDL.Vec(PropertyListing)], ['query']),
  'getListing' : IDL.Func([IDL.Nat], [PropertyListing], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchListings' : IDL.Func(
      [
        IDL.Opt(
          IDL.Variant({
            'timber' : IDL.Null,
            'commercial' : IDL.Null,
            'agricultural' : IDL.Null,
            'residential' : IDL.Null,
            'recreational' : IDL.Null,
          })
        ),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Float64),
      ],
      [IDL.Vec(PropertyListing)],
      ['query'],
    ),
  'submitContactInquiry' : IDL.Func([ContactInquiry], [], []),
  'updateListingStatus' : IDL.Func(
      [IDL.Nat, IDL.Variant({ 'sold' : IDL.Null, 'available' : IDL.Null })],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BrokerProfile = IDL.Record({
    'bio' : IDL.Text,
    'title' : IDL.Text,
    'name' : IDL.Text,
    'photoUrl' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Time = IDL.Int;
  const PropertyListing = IDL.Record({
    'zip' : IDL.Text,
    'status' : IDL.Variant({ 'sold' : IDL.Null, 'available' : IDL.Null }),
    'title' : IDL.Text,
    'created' : Time,
    'acreage' : IDL.Float64,
    'description' : IDL.Text,
    'propertyId' : IDL.Nat,
    'state' : IDL.Text,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'landType' : IDL.Variant({
      'timber' : IDL.Null,
      'commercial' : IDL.Null,
      'agricultural' : IDL.Null,
      'residential' : IDL.Null,
      'recreational' : IDL.Null,
    }),
    'price' : IDL.Nat,
    'county' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ContactInquiry = IDL.Record({
    'name' : IDL.Text,
    'propertyId' : IDL.Opt(IDL.Nat),
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBrokerProfile' : IDL.Func([BrokerProfile], [IDL.Nat], []),
    'addListing' : IDL.Func([PropertyListing], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllBrokerProfiles' : IDL.Func([], [IDL.Vec(BrokerProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeaturedListings' : IDL.Func([], [IDL.Vec(PropertyListing)], ['query']),
    'getListing' : IDL.Func([IDL.Nat], [PropertyListing], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchListings' : IDL.Func(
        [
          IDL.Opt(
            IDL.Variant({
              'timber' : IDL.Null,
              'commercial' : IDL.Null,
              'agricultural' : IDL.Null,
              'residential' : IDL.Null,
              'recreational' : IDL.Null,
            })
          ),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Float64),
        ],
        [IDL.Vec(PropertyListing)],
        ['query'],
      ),
    'submitContactInquiry' : IDL.Func([ContactInquiry], [], []),
    'updateListingStatus' : IDL.Func(
        [IDL.Nat, IDL.Variant({ 'sold' : IDL.Null, 'available' : IDL.Null })],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };