/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BrokerProfile {
  'bio' : string,
  'title' : string,
  'name' : string,
  'photoUrl' : string,
  'email' : string,
  'phone' : string,
}
export interface ContactInquiry {
  'name' : string,
  'propertyId' : [] | [bigint],
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface PropertyListing {
  'zip' : string,
  'status' : { 'sold' : null } |
    { 'available' : null },
  'title' : string,
  'created' : Time,
  'acreage' : number,
  'description' : string,
  'propertyId' : bigint,
  'state' : string,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'landType' : { 'timber' : null } |
    { 'commercial' : null } |
    { 'agricultural' : null } |
    { 'residential' : null } |
    { 'recreational' : null },
  'price' : bigint,
  'county' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBrokerProfile' : ActorMethod<[BrokerProfile], bigint>,
  'addListing' : ActorMethod<[PropertyListing], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllBrokerProfiles' : ActorMethod<[], Array<BrokerProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeaturedListings' : ActorMethod<[], Array<PropertyListing>>,
  'getListing' : ActorMethod<[bigint], PropertyListing>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchListings' : ActorMethod<
    [
      [] | [
        { 'timber' : null } |
          { 'commercial' : null } |
          { 'agricultural' : null } |
          { 'residential' : null } |
          { 'recreational' : null }
      ],
      [] | [bigint],
      [] | [bigint],
      [] | [number],
    ],
    Array<PropertyListing>
  >,
  'submitContactInquiry' : ActorMethod<[ContactInquiry], undefined>,
  'updateListingStatus' : ActorMethod<
    [bigint, { 'sold' : null } | { 'available' : null }],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];