/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface PropertyListing {
    zip: string;
    status: Variant_sold_available;
    title: string;
    created: Time;
    acreage: number;
    description: string;
    propertyId: bigint;
    state: string;
    imageUrl: string;
    isFeatured: boolean;
    landType: Variant_timber_commercial_agricultural_residential_recreational;
    price: bigint;
    county: string;
}
export interface ContactInquiry {
    name: string;
    propertyId?: bigint;
    email: string;
    message: string;
    timestamp: Time;
    phone: string;
}
export interface UserProfile {
    name: string;
}
export interface BrokerProfile {
    bio: string;
    title: string;
    name: string;
    photoUrl: string;
    email: string;
    phone: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_sold_available {
    sold = "sold",
    available = "available"
}
export enum Variant_timber_commercial_agricultural_residential_recreational {
    timber = "timber",
    commercial = "commercial",
    agricultural = "agricultural",
    residential = "residential",
    recreational = "recreational"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBrokerProfile(profile: BrokerProfile): Promise<bigint>;
    addListing(listing: PropertyListing): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllBrokerProfiles(): Promise<Array<BrokerProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFeaturedListings(): Promise<Array<PropertyListing>>;
    getListing(id: bigint): Promise<PropertyListing>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchListings(landType: Variant_timber_commercial_agricultural_residential_recreational | null, minPrice: bigint | null, maxPrice: bigint | null, minAcreage: number | null): Promise<Array<PropertyListing>>;
    submitContactInquiry(inquiry: ContactInquiry): Promise<void>;
    updateListingStatus(id: bigint, status: Variant_sold_available): Promise<void>;
}
import type { ContactInquiry as _ContactInquiry, PropertyListing as _PropertyListing, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBrokerProfile(arg0: BrokerProfile): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addBrokerProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBrokerProfile(arg0);
            return result;
        }
    }
    async addListing(arg0: PropertyListing): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addListing(to_candid_PropertyListing_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addListing(to_candid_PropertyListing_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllBrokerProfiles(): Promise<Array<BrokerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBrokerProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBrokerProfiles();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedListings(): Promise<Array<PropertyListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedListings();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedListings();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListing(arg0: bigint): Promise<PropertyListing> {
        if (this.processError) {
            try {
                const result = await this.actor.getListing(arg0);
                return from_candid_PropertyListing_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListing(arg0);
            return from_candid_PropertyListing_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchListings(arg0: Variant_timber_commercial_agricultural_residential_recreational | null, arg1: bigint | null, arg2: bigint | null, arg3: number | null): Promise<Array<PropertyListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchListings(to_candid_opt_n15(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg3));
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchListings(to_candid_opt_n15(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg3));
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitContactInquiry(arg0: ContactInquiry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactInquiry(to_candid_ContactInquiry_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactInquiry(to_candid_ContactInquiry_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateListingStatus(arg0: bigint, arg1: Variant_sold_available): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateListingStatus(arg0, to_candid_variant_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateListingStatus(arg0, to_candid_variant_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_PropertyListing_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyListing): PropertyListing {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    zip: string;
    status: {
        sold: null;
    } | {
        available: null;
    };
    title: string;
    created: _Time;
    acreage: number;
    description: string;
    propertyId: bigint;
    state: string;
    imageUrl: string;
    isFeatured: boolean;
    landType: {
        timber: null;
    } | {
        commercial: null;
    } | {
        agricultural: null;
    } | {
        residential: null;
    } | {
        recreational: null;
    };
    price: bigint;
    county: string;
}): {
    zip: string;
    status: Variant_sold_available;
    title: string;
    created: Time;
    acreage: number;
    description: string;
    propertyId: bigint;
    state: string;
    imageUrl: string;
    isFeatured: boolean;
    landType: Variant_timber_commercial_agricultural_residential_recreational;
    price: bigint;
    county: string;
} {
    return {
        zip: value.zip,
        status: from_candid_variant_n13(_uploadFile, _downloadFile, value.status),
        title: value.title,
        created: value.created,
        acreage: value.acreage,
        description: value.description,
        propertyId: value.propertyId,
        state: value.state,
        imageUrl: value.imageUrl,
        isFeatured: value.isFeatured,
        landType: from_candid_variant_n14(_uploadFile, _downloadFile, value.landType),
        price: value.price,
        county: value.county
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sold: null;
} | {
    available: null;
}): Variant_sold_available {
    return "sold" in value ? Variant_sold_available.sold : "available" in value ? Variant_sold_available.available : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    timber: null;
} | {
    commercial: null;
} | {
    agricultural: null;
} | {
    residential: null;
} | {
    recreational: null;
}): Variant_timber_commercial_agricultural_residential_recreational {
    return "timber" in value ? Variant_timber_commercial_agricultural_residential_recreational.timber : "commercial" in value ? Variant_timber_commercial_agricultural_residential_recreational.commercial : "agricultural" in value ? Variant_timber_commercial_agricultural_residential_recreational.agricultural : "residential" in value ? Variant_timber_commercial_agricultural_residential_recreational.residential : "recreational" in value ? Variant_timber_commercial_agricultural_residential_recreational.recreational : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PropertyListing>): Array<PropertyListing> {
    return value.map((x)=>from_candid_PropertyListing_n11(_uploadFile, _downloadFile, x));
}
function to_candid_ContactInquiry_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContactInquiry): _ContactInquiry {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyListing_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyListing): _PropertyListing {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_timber_commercial_agricultural_residential_recreational | null): [] | [{
        timber: null;
    } | {
        commercial: null;
    } | {
        agricultural: null;
    } | {
        residential: null;
    } | {
        recreational: null;
    }] {
    return value === null ? candid_none() : candid_some(to_candid_variant_n4(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    propertyId?: bigint;
    email: string;
    message: string;
    timestamp: Time;
    phone: string;
}): {
    name: string;
    propertyId: [] | [bigint];
    email: string;
    message: string;
    timestamp: _Time;
    phone: string;
} {
    return {
        name: value.name,
        propertyId: value.propertyId ? candid_some(value.propertyId) : candid_none(),
        email: value.email,
        message: value.message,
        timestamp: value.timestamp,
        phone: value.phone
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    zip: string;
    status: Variant_sold_available;
    title: string;
    created: Time;
    acreage: number;
    description: string;
    propertyId: bigint;
    state: string;
    imageUrl: string;
    isFeatured: boolean;
    landType: Variant_timber_commercial_agricultural_residential_recreational;
    price: bigint;
    county: string;
}): {
    zip: string;
    status: {
        sold: null;
    } | {
        available: null;
    };
    title: string;
    created: _Time;
    acreage: number;
    description: string;
    propertyId: bigint;
    state: string;
    imageUrl: string;
    isFeatured: boolean;
    landType: {
        timber: null;
    } | {
        commercial: null;
    } | {
        agricultural: null;
    } | {
        residential: null;
    } | {
        recreational: null;
    };
    price: bigint;
    county: string;
} {
    return {
        zip: value.zip,
        status: to_candid_variant_n3(_uploadFile, _downloadFile, value.status),
        title: value.title,
        created: value.created,
        acreage: value.acreage,
        description: value.description,
        propertyId: value.propertyId,
        state: value.state,
        imageUrl: value.imageUrl,
        isFeatured: value.isFeatured,
        landType: to_candid_variant_n4(_uploadFile, _downloadFile, value.landType),
        price: value.price,
        county: value.county
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_sold_available): {
    sold: null;
} | {
    available: null;
} {
    return value == Variant_sold_available.sold ? {
        sold: null
    } : value == Variant_sold_available.available ? {
        available: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_timber_commercial_agricultural_residential_recreational): {
    timber: null;
} | {
    commercial: null;
} | {
    agricultural: null;
} | {
    residential: null;
} | {
    recreational: null;
} {
    return value == Variant_timber_commercial_agricultural_residential_recreational.timber ? {
        timber: null
    } : value == Variant_timber_commercial_agricultural_residential_recreational.commercial ? {
        commercial: null
    } : value == Variant_timber_commercial_agricultural_residential_recreational.agricultural ? {
        agricultural: null
    } : value == Variant_timber_commercial_agricultural_residential_recreational.residential ? {
        residential: null
    } : value == Variant_timber_commercial_agricultural_residential_recreational.recreational ? {
        recreational: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
